"""empty message

Revision ID: 875ab8831c0e
Revises: 3d359390f318
Create Date: 2024-01-05 17:24:06.878539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875ab8831c0e'
down_revision = '3d359390f318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
